In [1]:
import pandas as pd
import os
import blpapi

In [ ]:
import blpapi
import pandas as pd

# Define constants for the API session
SESSION_STARTED = blpapi.Name("SessionStarted")
SESSION_STARTUP_FAILURE = blpapi.Name("SessionStartupFailure")
SERVICE_OPENED = blpapi.Name("ServiceOpened")
SERVICE_OPEN_FAILURE = blpapi.Name("ServiceOpenFailure")
ERROR_INFO = blpapi.Name("ErrorInfo")
SECURITY_DATA = blpapi.Name("securityData")

In [167]:
# --- Main Function to Get Bulk Historical Data ---
def get_bdh_data(tickers, fields, start_date, end_date):
    """
    Downloads historical data (BDH) from the Bloomberg API.
    """
    # Boilerplate connection logic
    sessionOptions = blpapi.SessionOptions()
    sessionOptions.setServerHost('localhost')
    sessionOptions.setServerPort(8194)
    session = blpapi.Session(sessionOptions)

    if not session.start():
        print("Failed to start session.")
        return

    if not session.openService("//blp/refdata"):
        print("Failed to open //blp/refdata")
        return


    refDataService = session.getService("//blp/refdata")
    request = refDataService.createRequest("HistoricalDataRequest")

    # Add tickers and fields to the request
    for ticker in tickers:
        request.getElement("securities").appendValue(ticker)
    for field in fields:
        print(field)
        request.getElement("fields").appendValue(field)

    # Set request parameters
    request.set("periodicitySelection", "DAILY")
    request.set("startDate", start_date)
    request.set("endDate", end_date)

    session.sendRequest(request)
    
    all_data = []
    
    # Process the response events
    while(True):
        ev = session.nextEvent(500)
        for msg in ev:
            if msg.hasElement(SECURITY_DATA):
                sec_data = msg.getElement(SECURITY_DATA)
                ticker = sec_data.getElementAsString("security")
                field_data = sec_data.getElement("fieldData")
                for i in range(field_data.numValues()):
                    row = field_data.getValueAsElement(i)
                    date = row.getElementAsDatetime("date")#.date()
                    for field in fields:
                        if row.hasElement(field):
                            value = row.getElementAsFloat(field)
                            all_data.append([date, ticker, field, value])
        if ev.eventType() == blpapi.Event.RESPONSE:
            break
            
    session.stop()
    
    # Convert the received data to a pandas DataFrame
    df = pd.DataFrame(all_data, columns=['date', 'ticker', 'field', 'value'])
    # Pivot the table to a more usable format
    pivot_df = df.pivot_table(index='date', columns=['ticker', 'field'], values='value')
    pivot_df['ticker'] = list( set( [i[0] for i in pivot_df.columns] ) )[0]
    pivot_df.columns = [i[1] for i in pivot_df.columns ][:-1] + ['ticker']
    
    return pivot_df

In [168]:
tickers_to_load = ["MSFT US Equity"]
esg_score_filed_lst = ['BEST_TOTAL_ESG_SCORE', 'BEST_ENVIRONMENT_SCORE','BEST_SOCIAL_SCORE','BEST_GOVERNANCE_SCORE','BEST_ESG_DISCLOSURE_SCORE',
'ESG_DISCLOSURE_SCORE','ESG_RISK_SCORE','ESG_SCORE','ENVIRONMENT_SCORE','SOCIAL_SCORE','GOVERNANCE_SCORE', 'CARBON_EMISSION_SCORE',
'SUSTAINABILITY_SCORE','ESG_RATING','ESG_COMPOSITE_SCORE','ESG_OPPORTUNITY_SCORE','ESG_CONTROVERSY_SCORE','ESG_CARBON_DISCLOSURE_SCORE']

fields_to_load = ["PX_LAST", "PX_VOLUME"] + esg_score_filed_lst
start = "20000101"
end = "20250912"

historical_data = get_bdh_data(tickers_to_load, fields_to_load, start, end)

if historical_data is not None:
    print("Successfully downloaded data:")
    display(historical_data.head())

PX_LAST
PX_VOLUME
BEST_TOTAL_ESG_SCORE
BEST_ENVIRONMENT_SCORE
BEST_SOCIAL_SCORE
BEST_GOVERNANCE_SCORE
BEST_ESG_DISCLOSURE_SCORE
ESG_DISCLOSURE_SCORE
ESG_RISK_SCORE
ESG_SCORE
ENVIRONMENT_SCORE
SOCIAL_SCORE
GOVERNANCE_SCORE
CARBON_EMISSION_SCORE
SUSTAINABILITY_SCORE
ESG_RATING
ESG_COMPOSITE_SCORE
ESG_OPPORTUNITY_SCORE
ESG_CONTROVERSY_SCORE
ESG_CARBON_DISCLOSURE_SCORE
Successfully downloaded data:
            ESG_SCORE  GOVERNANCE_SCORE  PX_LAST   PX_VOLUME  SOCIAL_SCORE  \
date
2000-01-03        NaN               NaN  58.2813  53236000.0           NaN
2000-01-04        NaN               NaN  56.3125  54094400.0           NaN
2000-01-05        NaN               NaN  56.9063  64059600.0           NaN
2000-01-06        NaN               NaN  55.0000  54976600.0           NaN
2000-01-07        NaN               NaN  55.7188  62013600.0           NaN

                    ticker
date
2000-01-03  MSFT US Equity
2000-01-04  MSFT US Equity
2000-01-05  MSFT US Equity
2000-01-06  MSFT US Equity
2000-01-07  MSFT US Equity

In [169]:
display(historical_data.head())

,ESG_SCORE,GOVERNANCE_SCORE,PX_LAST,PX_VOLUME,SOCIAL_SCORE,ticker
date,,,,,,
2000-01-03,NaN,NaN,58.2813,53236000.0,NaN,MSFT US Equity
2000-01-04,NaN,NaN,56.3125,54094400.0,NaN,MSFT US Equity
2000-01-05,NaN,NaN,56.9063,64059600.0,NaN,MSFT US Equity
2000-01-06,NaN,NaN,55.0000,54976600.0,NaN,MSFT US Equity
2000-01-07,NaN,NaN,55.7188,62013600.0,NaN,MSFT US Equity